formacion_doctrine:
    resource: "@FormacionDoctrineBundle/Controller/"
    type:     annotation
    prefix:   /

formacion_route:
    resource: "@FormacionRouteBundle/Controller/"
    type:     annotation
    prefix:   /route

formacion_solid:
    resource: "@FormacionSolidBundle/Controller/"
    type:     annotation
    prefix:   /solid

