<?php

namespace Formacion\DoctrineBundle\Repository;

/**
 * AristaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AristaRepository extends \Doctrine\ORM\EntityRepository
{
}
